run:
  timeout: 5m
  go: "1.23"
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    shadow: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/insider/insider-messaging
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  funlen:
    lines: 100
    statements: 50
  errcheck:
    check-type-assertions: true
    check-blank: true
  staticcheck:
    checks: ["all"]
  unused:
    check-exported: false
  gosec:
    severity: medium
    confidence: medium

linters:
  # Use enable instead of disable-all to avoid implicit typecheck
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - revive
    - copyloopvar
  disable:
    - typecheck
  fast: false

issues:
  exclude-dirs:
    - vendor
    - docs
    - .git
  exclude-files:
    - ".*\\.pb\\.go$"
  exclude-rules:
    # Test files
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - goconst
        - gosec
    # Main/cmd files
    - path: cmd/
      linters:
        - gochecknoinits
    # Exclude all external dependency issues
    - path: ".*/go/pkg/mod/.*"
      linters:
        - typecheck
        - gosec
        - staticcheck
        - govet
        - errcheck
        - unused
        - ineffassign
        - misspell
    # Exclude Go version compatibility issues completely
    - text: "file requires newer Go version"
      linters:
        - typecheck
    - text: "application built with go1.23"
      linters:
        - typecheck
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 3